const REQUEST_POSTS = 'REQUEST_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const FAIL_POSTS = 'FAIL_POSTS';
const RESET_POSTS = 'RESET_POSTS';
const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
const SELECT_ITEM = 'SELECT_ITEM';
const UPDATE_ITEM_VALUE = 'UPDATE_ITEM_VALUE';
const RECEIVE_ITEM = 'RECEIVE_ITEM';
const REQUEST_ASSETS = 'REQUEST_ASSETS';
const RECEIVE_ASSETS = 'RECEIVE_ASSETS';

export {
  REQUEST_POSTS,
  RECEIVE_ITEM,
  RECEIVE_POSTS,
  FAIL_POSTS,
  RESET_POSTS,
  SELECT_ITEM,
  INVALIDATE_SUBREDDIT,
  UPDATE_ITEM_VALUE,
  REQUEST_ASSETS,
  RECEIVE_ASSETS,
};
