const REQUEST_POSTS = 'REQUEST_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const FAIL_POSTS = 'FAIL_POSTS';
const RESET_POSTS = 'RESET_POSTS';
const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
const SELECT_ITEM = 'SELECT_ITEM';
const UPDATE_ITEM_VALUE = 'UPDATE_ITEM_VALUE';

export {
  REQUEST_POSTS,
  RECEIVE_POSTS,
  FAIL_POSTS,
  RESET_POSTS,
  SELECT_ITEM,
  INVALIDATE_SUBREDDIT,
  UPDATE_ITEM_VALUE,
};
